{% set name = "guietta" %}
{% set version = "1.6.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 284698ffce06455e984fb3589cf4f4809c16aac00b1f15fd44e7240a8a7a5bff

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - pyside2

# Test is done in run_test.sh, because we need to start a
# virtual framebuffer or the PySide2/PyQt imports will fail.
about:
  home: https://github.com/alfiopuglisi/guietta
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Simple GUI builder for Python
  description: |
    guietta is a tool to quickly create simple GUIs,
    built on top of QT.
  doc_url: https://guietta.readthedocs.io/
  dev_url: https://github.com/alfiopuglisi/guietta

extra:
  recipe-maintainers:
    - alfiopuglisi
